driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["winrm_port"] %>
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012r2

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[asp_core::default]
