---
# driver:
#   name: ec2
#
# provisioner:
#   name: chef_solo
#
platforms:
  - name: windows2012r2

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[asp_core::default]
    attributes:
