name 'asp_core'
maintainer 'Dan Webb'
maintainer_email 'dan.webb@damacus.io'
license 'Apache v2.0'
description 'Installs/Configures asp_core'
long_description 'Installs/Configures asp_core'
version '0.1.0'
issues_url 'https://github.com/damacus/asp_core/issues'
source_url 'https://github.com/damacus/asp_core'

depends 'iis'
