name 'asp_core'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures asp_core'
long_description 'Installs/Configures asp_core'
version '0.1.0'
issues_url 'https://github.com/damacus/asp_core/issues'
source_url 'https://github.com/damacus/asp_core'

depends 'iis'
